### ISSUE TITLE
ファイル分けた場合、pre-requestもテストファイル分実行される

### ISSUE THREAD

**Issue by kenichiroMori** [cloudpack/Rorschach#19]
テストファイルを分けた場合、pre-requestもテストファイルに書き込む必要があって冗長。
ただ、pre-requestも分けたい場合もありそうなので、デフォルトは用意しておき、テストファイルにpre-requestの記述があればそっち有効みたいな設定が必要。

**Comment by ghost** [comment]
@kenichiroMori 
pre-request.yml

``` yaml
-
  url: /auth
  method: GET
  bind:
    api-token: data.token
```

test.yml

``` yaml
base: http://localhost
pre-request: pre-request.yml
request:
  -
    url: /users
```

こんな実装はありです？
ファイル単位で実行はされてしまいますが。
