### ISSUE TITLE
configを切り出したい

### ISSUE THREAD

**Issue by kenichiroMori** [cloudpack/Rorschach#20]
実行時のbindや、テストファイルで冗長な箇所を予め設定ファイル等に切り出して実行時に読み出したい

**Comment by shinichi-takahashi** [comment]
ちょっと何言ってるかわかんないです。

**Comment by shinichi-takahashi** [comment]
base.yml

```
base:
  url: hoge
  bind: 
    - hoge: fuga
    - piyo: funya
```

みたいなのを食わせたいってこと？
